
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'traffic'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'traffic'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  traffic:
    materialized: view
    #weather_conditions:  
    #  materialized: view
    #  description: "A dbt model for weather conditions"
    #  columns:
    #    - name: locationid
    #      description: "Location ID"
    #    - name: congestionlevelid
    #      description: "Congestion Level ID"

    #rain_congestion_levels:
    # materialized: view
    #  description: "Find congestion levels during heavy rain"
    #  columns:
    #    - name: sectionid
    #      description: "Section ID"
    #    - name: congestionlevelid
    #      description: "Congestion Level ID"
    #    - name: traveltime
    #      description: "Travel Time"
    #    - name: travelspeed
    #      description: "Travel Speed"
    #    - name: locationname
    #      description: "Location Name"
    #    - name: elementname
    #      description: "Element Name"
    #    - name: starttime
    #      description: "Start Time"
    #    - name: endtime
    #      description: "End Time"
    #    - name: parametername
    #      description: "Parameter Name"
    #    - name: parameterunit
    #      description: "Parameter Unit"

