# example profiles.yml file
traffic:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 172.21.0.5
      user: postgres
      password: postgres
      port: 5432
      dbname: postgres
      schema: dbt_traffic
      threads: 4
